name: sport_elite_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.0
  smooth_page_indicator: ^1.0.0+2
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.5+3
  path: ^1.8.1
  image_cropper: ^2.0.3
  path_provider: ^2.0.11
  firebase_storage: ^10.2.18
  flutter_zoom_drawer: ^3.0.2
  auto_size_text: ^3.0.0
  expandable: ^5.0.1
  # Firebase
  firebase_core: ^1.20.0
  firebase_auth: ^3.3.20
  cloud_firestore: ^3.4.3
  email_validator: ^2.0.1
  google_sign_in: ^5.3.3
  flutter_facebook_auth: ^4.3.4+2
  shared_preferences: ^2.0.15
  shared_preferences_android: ^2.0.12
  modal_progress_hud_nsn: ^0.2.1
  bubble: ^1.2.1
  flutter_chat_bubble: ^2.0.0
  flutter_slidable: ^2.0.0
  provider: ^6.0.3
  sizer: ^2.0.15
  timeago: ^3.2.2
  cached_network_image: ^3.2.1
  google_fonts: ^2.2.0
  intl: ^0.17.0
  uuid: ^3.0.6
  emoji_picker_flutter: ^1.3.0
  file_picker: ^3.0.4
  flutter_downloader: ^1.8.1
  lecle_downloads_path_provider: ^0.0.2+7
  permission_handler: ^10.0.0
  firebase_messaging: ^12.0.1
  firebase_database: ^9.0.20
  flutter_local_notifications: ^9.7.0
  device_info: ^2.0.3
  flutter_native_timezone: ^2.0.0
  image: ^3.2.0
  flutter_background_service: ^2.1.3
  device_info_plus: ^4.0.1
  flutter_screenutil: ^5.5.3+2
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/placeholders/
